In [75]:
import numpy as np

In [76]:
version= np.version.version

print(version)


1.16.4


In [77]:
a = np.random.random((2,3,5))
print(a)


[[[0.24415195 0.41322901 0.36427125 0.76021976 0.16664567]
  [0.43202396 0.92503932 0.25860787 0.94071306 0.13241052]
  [0.48776626 0.63288691 0.16192691 0.69595825 0.10070979]]

 [[0.28437908 0.79967784 0.83398322 0.49179019 0.55271418]
  [0.5558456  0.72278854 0.30195312 0.45255079 0.71441135]
  [0.68386136 0.10011046 0.30753396 0.36215418 0.21795102]]]


In [78]:
b = np.zeros((5,2,3))+1
print(b)

#b = np.full((5,2,3), 1)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [79]:
#7 and #8: No, they are not. To check if they are the same size we can try summing them – 
#if it works, then they are the same size

#print(sum(a,b))

In [80]:
#c = np.arange(4).reshape((2,2))

c= np.transpose(b.reshape(5,3,2))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [110]:
d= (a+c)
print(d)

[[[1.24415195 1.41322901 1.36427125 1.76021976 1.16664567]
  [1.43202396 1.92503932 1.25860787 1.94071306 1.13241052]
  [1.48776626 1.63288691 1.16192691 1.69595825 1.10070979]]

 [[1.28437908 1.79967784 1.83398322 1.49179019 1.55271418]
  [1.5558456  1.72278854 1.30195312 1.45255079 1.71441135]
  [1.68386136 1.10011046 1.30753396 1.36215418 1.21795102]]]


In [111]:
e= (a*c)
print(e)

[[[0.24415195 0.41322901 0.36427125 0.76021976 0.16664567]
  [0.43202396 0.92503932 0.25860787 0.94071306 0.13241052]
  [0.48776626 0.63288691 0.16192691 0.69595825 0.10070979]]

 [[0.28437908 0.79967784 0.83398322 0.49179019 0.55271418]
  [0.5558456  0.72278854 0.30195312 0.45255079 0.71441135]
  [0.68386136 0.10011046 0.30753396 0.36215418 0.21795102]]]


In [112]:
#e=a because c is all 1. essentially you are multiplying all of a indexes with 1 which will give you the same answer. 
x=np.array_equal(a,e)
print(x)

True


In [113]:
#Q14
d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)
print(d_mean)

1.4699421788953615


In [114]:
#Q15
f = np.empty((2,3,5))

In [86]:
#Q16

for value in f[:,:,:]: 
    if value > d_min and value < d_mean:
        f.fill(25)
    elif value > d_mean and < d_max: 
        f.fill(75)
    elif value == d_mean:
        f.fill(50)
    elif value == d_min:
        f.fill(0)
    elif value == d_max:
        f.fill(100)


SyntaxError: invalid syntax (<ipython-input-86-9763360da023>, line 6)

In [87]:
#Q16
for x in range(0, f[0]):
    for y in range(1, f[1]): 
        for z in range(0, f[2]):
            f.put[x,y,z] = 25

TypeError: only integer scalar arrays can be converted to a scalar index

In [88]:
for x in d:
    for y in x: 
        if y > d_min and value < d_mean:
            f.fill[:](25)
        elif y > d_mean:
            f.fill[:](75)
        elif y == d_mean:   
            f.fill[:](50)
        elif y == d_min:
            f.fill[:](0)
        elif y == d_max:
            f.fill[:](100)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [89]:
for x in d:
    for y in x:
        if d[x][y] < d_mean and d[x][y] > d(min):
            print(y)
          #  f.fill(25)
#print(f)

IndexError: arrays used as indices must be of integer (or boolean) type

In [130]:
'''#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
    
    
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])'''

"#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\n\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n    \n    \n#17. Print d and f. Do you have your expected f?\nFor instance, if your d is:\narray([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.960

In [125]:
arr = np.random.random((2,3,5))

In [129]:
f = np.empty((2, 3, 5))

for i in d:
    for x in i:
        for y in x: 
            if y > d_min and value < d_mean:
                f[i,x,y] = 25
            elif y > d_mean:
                f[i,x,y] = 75
            elif y == d_mean:   
                f[i,x,y] = 50
            elif y == d_min:
                f[i,x,y] = 0
            elif y == d_max:
                f[i,x,y] = 100
                
print(f)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()