In [1]:
import numpy as np

In [7]:
version= np.version.version

print(version)


1.16.4


In [10]:
a = np.random.random((2,3,5))
print(a)


[[[0.16344238 0.47016532 0.54536298 0.36394877 0.61789109]
  [0.97504916 0.49305324 0.51685608 0.01141581 0.38274323]
  [0.90594645 0.78012469 0.40710866 0.55208101 0.62713536]]

 [[0.19081048 0.70236818 0.55601736 0.6962255  0.84481687]
  [0.35791125 0.0262636  0.32245985 0.85949691 0.21122119]
  [0.05409816 0.66831582 0.51811041 0.06461775 0.37260204]]]


In [23]:
b = np.zeros((5,2,3))+1
print(b)

#b = np.full((5,2,3), 1)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [18]:
#7 and #8: No, they are not. To check if they are the same size we can try summing them – 
#if it works, then they are the same size

#print(sum(a,b))

In [30]:
#c = np.arange(4).reshape((2,2))

c= np.transpose(b.reshape(5,3,2))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [32]:
d= sum(a+c)
print(d)

[[2.35425286 3.1725335  3.10138034 3.06017427 3.46270796]
 [3.33296041 2.51931684 2.83931593 2.87091271 2.59396442]
 [2.96004461 3.4484405  2.92521906 2.61669876 2.9997374 ]]


In [35]:
print(a)
print(d)

[[[0.16344238 0.47016532 0.54536298 0.36394877 0.61789109]
  [0.97504916 0.49305324 0.51685608 0.01141581 0.38274323]
  [0.90594645 0.78012469 0.40710866 0.55208101 0.62713536]]

 [[0.19081048 0.70236818 0.55601736 0.6962255  0.84481687]
  [0.35791125 0.0262636  0.32245985 0.85949691 0.21122119]
  [0.05409816 0.66831582 0.51811041 0.06461775 0.37260204]]]
[[2.35425286 3.1725335  3.10138034 3.06017427 3.46270796]
 [3.33296041 2.51931684 2.83931593 2.87091271 2.59396442]
 [2.96004461 3.4484405  2.92521906 2.61669876 2.9997374 ]]


In [36]:
e=a*c
print(e)

[[[0.16344238 0.47016532 0.54536298 0.36394877 0.61789109]
  [0.97504916 0.49305324 0.51685608 0.01141581 0.38274323]
  [0.90594645 0.78012469 0.40710866 0.55208101 0.62713536]]

 [[0.19081048 0.70236818 0.55601736 0.6962255  0.84481687]
  [0.35791125 0.0262636  0.32245985 0.85949691 0.21122119]
  [0.05409816 0.66831582 0.51811041 0.06461775 0.37260204]]]


In [48]:
#e=a because c is all 1. essentially you are multiplying all of a indexes with 1 which will give you the same answer. 
x=np.array_equal(a,e)
print(x)

True


In [39]:
d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)

2.9505106374465453


In [41]:
f =np.empty((2, 3, 5))

In [49]:
for x in d: 
    if index[x] < d_mean and index[x] > d(min):
        f.append(x)
    else: f.append(25)
print(f)

NameError: name 'index' is not defined